# Generated by Django 3.2.6 on 2021-08-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210808_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagoroy',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='name'),
            preserve_default=False,
        ),
    ]
